name: Build

on:
  push:
  schedule:
  # Run every day at 5:20
  - cron: '20 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - platform: linux/amd64
          arch: x86_64
          image: docker.io/archlinux:base-devel

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true # TODO: Update submodule
    - name: Set up QEMU
      if: matrix.platform != 'linux/amd64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.platform }}
    - name: Build packages (${{ matrix.platform }})
      run: >
        docker run
        --rm
        --env BUILDER_UID=$(id -u)
        --env BUILDER_GID=$(id -g)
        --platform "${{ matrix.platform }}"
        --mount type=bind,src="$PWD",dst=/src/arch-repo-x86_64
        --workdir /src/arch-repo-x86_64
        --entrypoint /src/arch-repo-x86_64/src/docker-entrypoint
        ${{ matrix.image }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.arch }}
        path: build
        retention-days: 1
  
  release:
    if: github.repository == 'fwcd/arch-repo-x86_64'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true # TODO: Update submodules automatically
    - name: Download build artifacts for each architecture
      uses: actions/download-artifact@v3
      with:
        path: build
    - name: Build package database
      run: >
        docker run
        --rm
        --user "$(id -u):$(id -g)"
        --mount type=bind,src="$PWD",dst=/src/arch-repo-x86_64
        --workdir /src/arch-repo-x86_64
        --entrypoint /src/arch-repo-x86_64/src/build-db
        archlinux
    - name: List db packages
      run: ls -l db
    - name: Set up Git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Update PKGBUILDs and .SRCINFOs
      run: cp -r build/x86_64/src/ .
    - name: Commit updates
      run: |
        git add -A
        git commit --allow-empty -m "Update packages ($(date '+%Y-%m-%d-%H-%M'))"
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      run: git push
    - name: Publish release
      if: github.ref == 'refs/heads/main'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        tag="$(date '+%Y-%m-%d-%H-%M')"
        gh release create --title "$tag" "$tag" || true
        gh release upload --clobber "$tag" db/*
